spring:
  application:
    name : MiniPet

  datasource:
    url: jdbc:postgresql://localhost:5432/MiniPet
    username: Timur
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
